default: &default
  adapter: postgresql
  encoding: unicode
  username: d_prod
  password: daniel123
  host: localhost

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  database: blog_app_production
